### PR TITLE
Update README.md before archiving?

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by karthik** [comment]
It has not been moved though. These are the old logos and the other repo are the new logos.  These stickers are still in circulation. Do we just erase the past or leave this repo elsewhere?

**Comment by maelle** [comment]
As you prefer, at least the link to the new ones should be added? I'd prefer to archive the repo but again, as you prefer.

**Comment by karthik** [comment]
What does archiving a repo mean? It disappears from here?

**Comment by maelle** [comment]
No it becomes read only so it shows it's no longer maintained.

https://github.com/ropensci?utf8=✓&q=&type=archived&language=

**Comment by maelle** [comment]
* Made edits, no badge for the no software project any more 👼 

* Are you against archiving it?

**Comment by karthik** [comment]
ok, sounds good to archive now that I understand what it does.

**Comment by maelle** [comment]
Ok should I merge and archive?

**Comment by karthik** [comment]
Feel free to archive now.

**Pull request merged**
